project:
  type: website

website:
  title: "BVÖGD Berlin Brandenburg"
  site-url: https://jakobschumacher.github.io/bvoegdbb_website/
  navbar:
    left:
      - href: index.qmd
        text: Startseite
      - href: pages/mitgliedschaft.qmd
        text: Mitgliedschaft
      - href: pages/neuigkeiten.qmd
        text: "Veranstaltungen & Positionen"
      - href: pages/oegd.qmd
        text: Öffentlicher Gesundheitsdienst
      - href: pages/about.qmd
        text: Über
  page-footer: 
    left: "Copyright 2023 BVÖGD-BB" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



