project:
  type: website

website:
  title: "BVÖGD Berlin Brandenburg"
  site-url: https://jakobschumacher.github.io/bvoegdbb_website/
  navbar:
    left:
      - href: index.qmd
        text: Startseite
      - href: pages/mitgliedschaft.qmd
        text: Mitgliedschaft
      - href: pages/neuigkeiten.qmd
        text: Neuigkeiten
      - href: pages/about.qmd
        text: Über
  page-footer: 
    left: "Copyright 2023 Verband der Ärztinnen und Ärzte des Öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V." 
    right: 
      - href: pages/impressum.qmd
        text: Impressum & Datenschutz
      - icon: github
        href: https://github.com/



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



