project:
  type: website

website:
  title: "ÖGD Brandenburg Berlin"
  site-url: https://oegd-bb.de
  navbar:
    logo: img/logo_klein.png
    left:
      - href: index.qmd
        text: Startseite
      - href: pages/mitgliedschaft.qmd
        text: Mitgliedschaft
      - href: pages/neuigkeiten.qmd
        text: Neuigkeiten
      - href: pages/oegd.qmd
        text: ÖGD
      - href: pages/about.qmd
        text: Über
  page-footer: 
    left: "ÖGD Brandenburg Berlin" 
    right: 
      - href: pages/impressum.qmd#datenschutzerklärung
        text: Datenschutz
      - href: pages/impressum.qmd
        text: Impressum 
      - href: pages/impressum.qmd#copyright
        text: Copyright
      - href: pages/impressum.qmd#haftungshinweise
        text: Haftungshinweise
      - href: pages/impressum.qmd#bildquellen
        text: Bildquellen 
      - text: Fehlermeldung
        href: https://github.com/


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
