---
title: "Mitgliedschaft"
---


Alle Ärztinnen und Ärzte, Zahnärztinnen und Zahnärzte sowie Fachkräfte im Öffentlichen Gesundheitsdienst der Länder Brandenburg oder Berlin können Mitglied im Verband der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. werden.

Mit der Mitgliedschaft eröffnet sich die Möglichkeit, einander kennen zu lernen – ein nicht zu unterschätzender Aspekt!

Wir legen Wert auf ein von Toleranz und gegenseitiger Achtung geprägtes Miteinander und freuen uns über jedes neue Mitglied.
Gute Gründe für eine Mitgliedschaft

Als Mitglied im ÖGD-Landesverband Brandenburg und Berlin …

    können Sie an der Gestaltung des öffentlichen Gesundheitsdienstes aktiv mitwirken.
    werden Ihre beruflichen Interessen wirksam vertreten.
    sind Sie in über Entwicklungen im öffentlichen Gesundheitsdienst gut informiert.
    genießen Sie Unterstützung in beruflichen Rechtsfragen.
    profitieren Sie von den Vorteilen, die der Bundesverband (BVÖGD.de) bietet.
    können Sie auf Tagungs- und Schulungsangebote zurückgreifen und zu vergünstigten Konditionen am wissenschaftlichen Kongress des BVÖGD und BZÖG teilnehmen.
    beziehen Sie regelmäßig die digitale Ausgabe von impfbrief.de.

Wie werde ich Mitglied?

Den Aufnahmeantrag für die Mitgliedschaft finden Sie zum herunterladen hier (PDF). Bitte senden Sie das ausgedruckte und ausgefüllte Original (Aufnahmeantrag & Einzugsermächtigung) an:

 

Martina Hänel (Schatzmeisterin)

Handjerystr. 63

12161 Berlin

 

Bitte ermächtigen Sie den Verband der Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. zum Einzug des Jahresbeitrag damit wir das Beitragsverfahren für alle Beteiligten möglichst einfach zu gestalten können.

(Stand: 14.04.2018)