---
title: "Fortbildungsveranstaltung und Mitgliederversammlung des Landesverbandes Brandenburg und Berlin"
---


Am 08.06.2021 findet die Fortbildungsveranstaltung und Mitgliederversammlung des ÖGD-Landesverbandes Brandenburg und Berlin 2021 virtuell statt.

Das Thema der Fortbildungsveranstaltung ist "Öffentlicher Gesundheitsdienst in Zeiten der Pandemie".

Das Programm finden Sie (hier)
Wissenschaftlicher Kongress 2020: "Der Öffentliche Gesundheitsdienst – Große Gesundheitsziele fördern wir hier von klein auf" in Saarbrücken

Der gemeinsame 70. Bundeskongress von BVÖGD und BZÖG findet vom 23. bis 25. April 2020 in Saarbrücken statt.

Er steht unter dem Motto „Der Öffentliche Gesundheitsdienst – Große Gesundheitsziele fördern wir hier von klein auf“

Weitere Informationen finden Sie:  www.bvoegd-kongress.de
Wissenschaftlicher Kongress 2019: „Der Öffentliche Gesundheitsdienst – Mitten in der Gesellschaft “ in Kassel

Der gemeinsame 69. Bundeskongress von BVÖGD und BZÖG findet vom 04. bis 06. April 2019 in Zusammenarbeit mit der Gesellschaft für Hygiene, Umweltmedizin und Prävention e.V. (GHUP) in Kassel statt.

Er steht unter dem Motto „Der Öffentliche Gesundheitsdienst – Mitten in der Gesellschaft!“

Das Programm finden Sie (hier)
Fortbildungsveranstaltung und Mitgliederversammlung des Landesverbandes Brandenburg und Berlin

Am 25.02.2019 findet die Fortbildungsveranstaltung und Mitgliederversammlung des ÖGD-Landesverbandes Brandenburg und Berlin 2019 statt.

Das Thema der Fortbildungsveranstaltung ist "Gesundheitsschutz für Alle! Herausforderungen für den ÖGD bei der Tuberkulosefürsorge und der Beratung zu sexuell übertragbaren Krankheiten".

Das Programm finden Sie (hier)
Wissenschaftlicher Kongress 2018: „Der Öffentliche Gesundheitsdienst – jetzt erst recht!“ in Osnabrück

Der gemeinsame 68. Bundeskongress von BVÖGD und BZÖG findet vom 26. bis 28. April 2018 in Zusammenarbeit mit der Gesellschaft für Hygiene, Umweltmedizin und Prävention e.V. (GHUP) in Osnabrück statt.

Er steht unter dem Motto „Der Öffentliche Gesundheitsdienst – jetzt erst recht!“

Das Programm finden Sie (hier)
Wissenschaftlicher Kongress 2017: „Gesundheit für Alle“ in München

Der Bundeskongress im Jahr 2017 wurde vom 3. bis 5. Mai 2017 zusammen mit dem Bayerischen Landesamt für Lebensmitttelsicherheit (LGL) und der Gesellschaft für Hygiene, Umweltmedizin und Prävention e.V. (GHUP) in München ausgerichtet.

Weitere Informationen erhalten Sie (hier)
5. Nationale Impfkonferenz

Die 5. Nationale Impfkonferenz findet am 10.05. und 11.05.2017 in Oldenburg unter dem Motto „Impfen in unterschiedlichen Lebenswelten – Gemeinsam Impflücken schließen!“ statt. Das Programm und Abstracts sind auf der Webseite der Nationalen Impfkonferenz abrufbar.
Fortbildungsveranstaltung und Mitgliederversammlung des Landesverbandes Brandenburg und Berlin

Am 20.02.2017 findet die Fortbildungsveranstaltung zum Thema "Kinderschutz eine multiprofessionelle Aufgabe" und  Mitgliederversammlung des ÖGD-Landesverbandes Brandenburg und Berlin 2017 statt. Das Programm finden Sie hier (PDF).