---
title: "Impressum"
---

Im Impressum finden Sie gesetzlich vorgeschriebene Informationen zu den Herausgebern der Website und zur Abgrenzung von fremden Inhalten.

Aus Gründen der besseren Lesbarkeit wird auf oegd-bbg-berlin.de der Einfachheit halber nur die männliche Form verwendet. Sämtliche Personen- und Berufsbezeichnungen gelten jedoch gleichermaßen für alle Geschlechter.


## Herausgeber

Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V.
Der Verband vertritt Ärztinnen und Ärzte, Zahnärzte und andere Fachkräfte im Öffentlichen Gesundheitsdienst der Länder Brandenburg und Berlin

Vorsitzender:
Dr. Kristina Böhm
Redaktion

Martina Hänel
Telefon: +49 (0) 30 85 11 787
E-Mail: OeGDLandesverbandBBB(at)gmx.de

Inhaltlich verantwortlich gemäß Paragraf 55 Rundfunkstaatsvertrag (RfStV) und § 5 Telemediengesetz (TMG):
Vorstand des Verbandes der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V.
Haftungshinweise

Der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. prüft und aktualisiert die Informationen auf seiner Webseite ständig. Trotz aller Sorgfalt können sich die Daten verändert haben. Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen kann nicht übernommen werden. Gleiches gilt auch für alle anderen Websites, auf die mittels Hyperlink verwiesen wird. Der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. ist für den Inhalt der Website, die aufgrund einer solchen Verbindung erreicht wird, nicht verantwortlich.

Des Weiteren behält sich der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. das Recht vor, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.

Inhalt und Struktur der Websites des Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. sind urheberrechtlich geschützt.
Copyright

Sofern zur Verwendung von im Internetangebot veröffentlichten Inhalten spezielle Nutzungsbedingungen festgelegt sind, gelten diese vorrangig. Ein Download oder Ausdruck von Inhalten ausschließlich für den persönlichen Gebrauch sind gestattet. Alle Inhalte, Bilder oder Grafiken sind urheberrechtlich geschützt und dürfen nur mit schriftlicher Genehmigung des jeweiligen Rechteinhabers verwendet werden.

## Bildquellen 
Foto von <a href="https://unsplash.com/de/@markusspiske?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Markus Spiske</a> auf <a href="https://unsplash.com/de/fotos/P0klwkGbH_M?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  


Foto von <a href="https://unsplash.com/de/@jonasjacobsson?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jonas Jacobsson</a> auf <a href="https://unsplash.com/de/fotos/2xaF4TbjXT0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  