---
title: "Seien Sie Dabei: Werden Sie Mitglied"
---

:::: {.columns}

::: {.column width="25%"}
{{< iconify fluent number-circle-1-32-regular size=4x >}}
::: 
::: {.column width="75%"}
### Möglichkeit prüfen
Alle Ärztinnen und Ärzte, Zahnärztinnen und Zahnärzte sowie Fachkräfte im Öffentlichen Gesundheitsdienst der Länder Brandenburg oder Berlin können Mitglied werden.
::: 

::::



:::: {.columns}

::: {.column width="25%"}
{{< iconify fluent number-circle-2-32-regular size=4x >}}
::: 
::: {.column width="75%"}
### Vorteile der Mitgliedschaft
* Sie können an der Gestaltung des öffentlichen Gesundheitsdienstes aktiv mitwirken.
* Sie können Ihre beruflichen Interessen wirksam vertreten lassen.
* Sie sind über die Entwicklungen im öffentlichen Gesundheitsdienst gut informiert.
* Sie genießen Sie Unterstützung in beruflichen Rechtsfragen.
* Sie profitieren von den Vorteilen, die der Bundesverband [BVÖGD.de](https://bvoegd.de) bietet.
* Sie können Sie auf Fortbilden lassen 
* Sie können sich über die Facharztweiterbildung zum Facharzt ÖGW informieren
* Sie können zu vergünstigten Konditionen am wissenschaftlichen [Kongress des BVÖGD und BZÖG](https://bvoegd-kongress.de/) teilnehmen.

::: 

::::

:::: {.columns}
::: {.column width="25%"}
{{< iconify fluent number-circle-3-32-regular size=4x >}}
::: 
::: {.column width="75%"}
### Wichtige Dokumente kennen lernen
Lernen Sie die [Satzung](../documents/satzung.pdf) und die [Beitragsordnung](../documents/beitragsordnung.pdf) kennen 
::: 

::::


:::: {.columns}

::: {.column width="25%"}
{{< iconify fluent number-circle-4-32-regular size=4x >}}
::: 
::: {.column width="75%"}
### Aufnahmeantrag ausfüllen und abschicken
[Aufnahmeantrag und Einzugsermächtigung](../documents/Antrag_auf_Mitgliedschaft_Einzugsermaechtigung_2019-02-23.pdf) für die Mitgliedschaft herunterladen und ausfüllen.


Bitte senden Sie das ausgedruckte und ausgefüllte Original (Aufnahmeantrag & Einzugsermächtigung) an:

Martina Hänel (Schatzmeisterin)  
Handjerystr. 63  
12161 Berlin  
::: 

::::

