---
title: "Was ist der öffentlicher Gesundheitsdienst - Ein Überblick"
toc: false
---

Der Öffentliche Gesundheitsdienst spielt eine stille aber zentrale Rolle im Gesundheitswesen. 

Der Öffentliche Gesundheitsdienst kümmert sich vor allem um:

*    Gesundheitsschutz und -förderung
*    Prävention und Berichterstattung
*    Politikberatung

In Deutschland sind die Gesundheitsämter auf kommunaler Ebene angesiedelt. Sie bestehen aus einem Team von Experten, darunter Ärzte, Psychologen und Ingenieure. Ihre Aufgaben? Von der Beratung in medizinischen Fragen bis hin zur Überwachung von Trinkwasser und Hygiene.

Ein typisches Gesundheitsamt hat verschiedene Bereiche:

*    Amtsärztlicher Dienst
*    Infektionsschutz und Hygiene
*    Kinder- und Jugendgesundheitsdienst
*    Psychiatrie

Zusätzlich gibt es Bereiche wie Gesundheitsförderung, Beratung von Personengruppen mit gesundheitlichen Einschränkungen, Heilpraktikeraufsicht, Schädlingsbekämpfung, umweltbezogener Gesundheitsschutz, Zentrum für sexuelle Gesundheit und viele mehr.

Auf Landesebene gibt es die Landesstellen und auf Bundesebene spezialisierte Behörden wie das Robert-Koch Institut und das Paul-Ehrlich Institut. s
